name       : kactivities
version    : 5.65.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kactivities-5.65.0.tar.xz : 00a64654861cdff809be5f78931bfd671fe81841380b9c3926f75957c18f139b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
