name       : kactivities
version    : 5.28.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.28/kactivities-5.28.0.tar.xz : eba9db7aecd916df45803c566fa2b11f377d2f497cfdfbc6a263a1eb18a65198
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
