name       : kactivities
version    : 5.36.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.36/kactivities-5.36.0.tar.xz : 47eb6967336d4d985b079e5b5b44afc51d66e7ed3a85cea923e295e10a952340
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
