name       : kactivities
version    : 5.35.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.35/kactivities-5.35.0.tar.xz : 24307d4b8526aa5e140e83044d0bec390d0badfc5ba777557269e95df65ca211
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
