name       : kactivities
version    : 5.52.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kactivities-5.52.0.tar.xz : add14c6331d4a282ca8313a5a931f111cb85efaf13079035428c50e2f65c935d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
