name       : kactivities
version    : 5.51.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kactivities-5.51.0.tar.xz : 75a9f1302d75e90ad9dbfd153f6b4d8082d0d25754b394b4478c9a22c372d559
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
