name       : kactivities
version    : 5.75.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kactivities-5.75.0.tar.xz : d25fa31d9ad8bed6af1adbd589945494d1f5741e18e7bb5d67371749c6565e08
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : programming.library
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
