name       : kactivities
version    : 5.107.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/kactivities-5.107.0.tar.xz : 19b79539a72e5a8b13f7eb94789eb61a5d5945003a86aa121203017cf3139b29
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : programming.library
summary    : Core components for the KDE Activity concept
description: |
    KActivities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
